# Generated by Django 3.0.8 on 2020-07-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/')),
                ('title', models.CharField(max_length=20)),
                ('pub_date', models.CharField(max_length=20)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
    ]
